// Code generated by the Encore 1.50.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly auth: auth.ServiceClient
    public readonly buildings: buildings.ServiceClient
    public readonly conseil: conseil.ServiceClient
    public readonly dashboard: dashboard.ServiceClient
    public readonly issues: issues.ServiceClient
    public readonly notifications: notifications.ServiceClient
    public readonly owners: owners.ServiceClient
    public readonly seeder: seeder.ServiceClient
    public readonly suppliers: suppliers.ServiceClient
    public readonly units: units.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.auth = new auth.ServiceClient(base)
        this.buildings = new buildings.ServiceClient(base)
        this.conseil = new conseil.ServiceClient(base)
        this.dashboard = new dashboard.ServiceClient(base)
        this.issues = new issues.ServiceClient(base)
        this.notifications = new notifications.ServiceClient(base)
        this.owners = new owners.ServiceClient(base)
        this.seeder = new seeder.ServiceClient(base)
        this.suppliers = new suppliers.ServiceClient(base)
        this.units = new units.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listUsers as api_auth_list_users_listUsers } from "~backend/auth/list_users";
import { login as api_auth_login_login } from "~backend/auth/login";
import { register as api_auth_register_register } from "~backend/auth/register";
import { seedDemoUsers as api_auth_seed_seedDemoUsers } from "~backend/auth/seed";
import { toggleUser as api_auth_toggle_user_toggleUser } from "~backend/auth/toggle_user";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.listUsers = this.listUsers.bind(this)
            this.login = this.login.bind(this)
            this.register = this.register.bind(this)
            this.seedDemoUsers = this.seedDemoUsers.bind(this)
            this.toggleUser = this.toggleUser.bind(this)
        }

        public async listUsers(): Promise<ResponseType<typeof api_auth_list_users_listUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/users`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_list_users_listUsers>
        }

        /**
         * Authenticates a user and returns a JWT token.
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Registers a new user.
         */
        public async register(params: RequestType<typeof api_auth_register_register>): Promise<ResponseType<typeof api_auth_register_register>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/register`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_register_register>
        }

        public async seedDemoUsers(): Promise<ResponseType<typeof api_auth_seed_seedDemoUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/seed-demo`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_seed_seedDemoUsers>
        }

        public async toggleUser(params: RequestType<typeof api_auth_toggle_user_toggleUser>): Promise<ResponseType<typeof api_auth_toggle_user_toggleUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/users/toggle`, {method: "PATCH", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_toggle_user_toggleUser>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_buildings_create_create } from "~backend/buildings/create";
import { get as api_buildings_get_get } from "~backend/buildings/get";
import { list as api_buildings_list_list } from "~backend/buildings/list";
import { seedBuildings as api_buildings_seed_seedBuildings } from "~backend/buildings/seed";

export namespace buildings {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.seedBuildings = this.seedBuildings.bind(this)
        }

        /**
         * Creates a new building.
         */
        public async create(params: RequestType<typeof api_buildings_create_create>): Promise<ResponseType<typeof api_buildings_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/buildings`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_buildings_create_create>
        }

        /**
         * Retrieves detailed information about a specific building.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_buildings_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/buildings/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_buildings_get_get>
        }

        /**
         * Retrieves all buildings.
         */
        public async list(): Promise<ResponseType<typeof api_buildings_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/buildings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_buildings_list_list>
        }

        public async seedBuildings(): Promise<ResponseType<typeof api_buildings_seed_seedBuildings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/buildings/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_buildings_seed_seedBuildings>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_conseil_create_create } from "~backend/conseil/create";
import { get as api_conseil_get_get } from "~backend/conseil/get";
import { list as api_conseil_list_list } from "~backend/conseil/list";
import {
    createSupervision as api_conseil_supervise_createSupervision,
    listSupervisions as api_conseil_supervise_listSupervisions,
    updateSupervision as api_conseil_supervise_updateSupervision
} from "~backend/conseil/supervise";

export namespace conseil {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.createSupervision = this.createSupervision.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.listSupervisions = this.listSupervisions.bind(this)
            this.updateSupervision = this.updateSupervision.bind(this)
        }

        public async create(params: RequestType<typeof api_conseil_create_create>): Promise<ResponseType<typeof api_conseil_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conseil`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conseil_create_create>
        }

        public async createSupervision(params: RequestType<typeof api_conseil_supervise_createSupervision>): Promise<ResponseType<typeof api_conseil_supervise_createSupervision>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conseil/supervise`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conseil_supervise_createSupervision>
        }

        public async get(params: { buildingId: number }): Promise<ResponseType<typeof api_conseil_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conseil/${encodeURIComponent(params.buildingId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conseil_get_get>
        }

        public async list(): Promise<ResponseType<typeof api_conseil_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conseil`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conseil_list_list>
        }

        public async listSupervisions(params: { buildingId: number }): Promise<ResponseType<typeof api_conseil_supervise_listSupervisions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conseil/${encodeURIComponent(params.buildingId)}/supervisions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conseil_supervise_listSupervisions>
        }

        public async updateSupervision(params: RequestType<typeof api_conseil_supervise_updateSupervision>): Promise<ResponseType<typeof api_conseil_supervise_updateSupervision>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                status: params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/conseil/supervise/${encodeURIComponent(params.supervisionId)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_conseil_supervise_updateSupervision>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getStats as api_dashboard_stats_getStats } from "~backend/dashboard/stats";

export namespace dashboard {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getStats = this.getStats.bind(this)
        }

        /**
         * Retrieves dashboard statistics.
         */
        public async getStats(): Promise<ResponseType<typeof api_dashboard_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/dashboard/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dashboard_stats_getStats>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_issues_create_create } from "~backend/issues/create";
import { list as api_issues_list_list } from "~backend/issues/list";
import { seedIssues as api_issues_seed_seedIssues } from "~backend/issues/seed";
import { update as api_issues_update_update } from "~backend/issues/update";

export namespace issues {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.seedIssues = this.seedIssues.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new issue or maintenance request.
         */
        public async create(params: RequestType<typeof api_issues_create_create>): Promise<ResponseType<typeof api_issues_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/issues`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_issues_create_create>
        }

        /**
         * Retrieves all issues.
         */
        public async list(params: RequestType<typeof api_issues_list_list>): Promise<ResponseType<typeof api_issues_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                buildingId: params.buildingId === undefined ? undefined : String(params.buildingId),
                limit:      params.limit === undefined ? undefined : String(params.limit),
                status:     params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/issues`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_issues_list_list>
        }

        public async seedIssues(): Promise<ResponseType<typeof api_issues_seed_seedIssues>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/issues/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_issues_seed_seedIssues>
        }

        /**
         * Updates an existing issue status or assignment.
         */
        public async update(params: RequestType<typeof api_issues_update_update>): Promise<ResponseType<typeof api_issues_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                actualCost:     params.actualCost,
                assignedTo:     params.assignedTo,
                estimatedCost:  params.estimatedCost,
                status:         params.status,
                supplierRating: params.supplierRating,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/issues/${encodeURIComponent(params.id)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_issues_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { list as api_notifications_list_list } from "~backend/notifications/list";
import { markRead as api_notifications_mark_read_markRead } from "~backend/notifications/mark_read";
import { seedNotifications as api_notifications_seed_seedNotifications } from "~backend/notifications/seed";

export namespace notifications {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.list = this.list.bind(this)
            this.markRead = this.markRead.bind(this)
            this.seedNotifications = this.seedNotifications.bind(this)
        }

        /**
         * Retrieves all notifications.
         */
        public async list(params: RequestType<typeof api_notifications_list_list>): Promise<ResponseType<typeof api_notifications_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:      params.limit === undefined ? undefined : String(params.limit),
                unreadOnly: params.unreadOnly === undefined ? undefined : String(params.unreadOnly),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_list_list>
        }

        /**
         * Marks a notification as read.
         */
        public async markRead(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/notifications/${encodeURIComponent(params.id)}/read`, {method: "PATCH", body: undefined})
        }

        public async seedNotifications(): Promise<ResponseType<typeof api_notifications_seed_seedNotifications>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_seed_seedNotifications>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createOwnership as api_owners_create_ownership_createOwnership } from "~backend/owners/create_ownership";
import { getBuildingOwners as api_owners_get_building_owners_getBuildingOwners } from "~backend/owners/get_building_owners";
import { getOwnership as api_owners_get_ownership_getOwnership } from "~backend/owners/get_ownership";
import { list as api_owners_list_list } from "~backend/owners/list";
import { seed as api_owners_seed_seed } from "~backend/owners/seed";
import { updateOwnership as api_owners_update_ownership_updateOwnership } from "~backend/owners/update_ownership";

export namespace owners {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createOwnership = this.createOwnership.bind(this)
            this.getBuildingOwners = this.getBuildingOwners.bind(this)
            this.getOwnership = this.getOwnership.bind(this)
            this.list = this.list.bind(this)
            this.seed = this.seed.bind(this)
            this.updateOwnership = this.updateOwnership.bind(this)
        }

        public async createOwnership(params: RequestType<typeof api_owners_create_ownership_createOwnership>): Promise<ResponseType<typeof api_owners_create_ownership_createOwnership>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/owners/ownership`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_owners_create_ownership_createOwnership>
        }

        public async getBuildingOwners(params: { buildingId: number }): Promise<ResponseType<typeof api_owners_get_building_owners_getBuildingOwners>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/owners/building/${encodeURIComponent(params.buildingId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_owners_get_building_owners_getBuildingOwners>
        }

        public async getOwnership(params: { id: number }): Promise<ResponseType<typeof api_owners_get_ownership_getOwnership>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/owners/ownership/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_owners_get_ownership_getOwnership>
        }

        public async list(params: RequestType<typeof api_owners_list_list>): Promise<ResponseType<typeof api_owners_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                buildingId: params.buildingId === undefined ? undefined : String(params.buildingId),
                unitId:     params.unitId === undefined ? undefined : String(params.unitId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/owners`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_owners_list_list>
        }

        public async seed(): Promise<ResponseType<typeof api_owners_seed_seed>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/owners/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_owners_seed_seed>
        }

        public async updateOwnership(params: RequestType<typeof api_owners_update_ownership_updateOwnership>): Promise<ResponseType<typeof api_owners_update_ownership_updateOwnership>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                endDate:             params.endDate,
                isPrimaryResidence:  params.isPrimaryResidence,
                isRentalProperty:    params.isRentalProperty,
                notaryReference:     params.notaryReference,
                ownershipPercentage: params.ownershipPercentage,
                purchasePrice:       params.purchasePrice,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/owners/ownership/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_owners_update_ownership_updateOwnership>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { seedAll as api_seeder_seed_all_seedAll } from "~backend/seeder/seed_all";

export namespace seeder {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.seedAll = this.seedAll.bind(this)
        }

        public async seedAll(): Promise<ResponseType<typeof api_seeder_seed_all_seedAll>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/seed-all`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_seeder_seed_all_seedAll>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_suppliers_create_create } from "~backend/suppliers/create";
import { list as api_suppliers_list_list } from "~backend/suppliers/list";
import { seedSuppliers as api_suppliers_seed_seedSuppliers } from "~backend/suppliers/seed";

export namespace suppliers {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.seedSuppliers = this.seedSuppliers.bind(this)
        }

        /**
         * Creates a new supplier profile.
         */
        public async create(params: RequestType<typeof api_suppliers_create_create>): Promise<ResponseType<typeof api_suppliers_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/suppliers`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_suppliers_create_create>
        }

        /**
         * Retrieves all registered suppliers.
         */
        public async list(): Promise<ResponseType<typeof api_suppliers_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/suppliers`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_suppliers_list_list>
        }

        public async seedSuppliers(): Promise<ResponseType<typeof api_suppliers_seed_seedSuppliers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/suppliers/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_suppliers_seed_seedSuppliers>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_units_create_create } from "~backend/units/create";
import { get as api_units_get_get } from "~backend/units/get";
import { list as api_units_list_list } from "~backend/units/list";
import { seed as api_units_seed_seed } from "~backend/units/seed";
import { update as api_units_update_update } from "~backend/units/update";

export namespace units {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.seed = this.seed.bind(this)
            this.update = this.update.bind(this)
        }

        public async create(params: RequestType<typeof api_units_create_create>): Promise<ResponseType<typeof api_units_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/units`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_units_create_create>
        }

        public async get(params: { id: number }): Promise<ResponseType<typeof api_units_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/units/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_units_get_get>
        }

        public async list(params: RequestType<typeof api_units_list_list>): Promise<ResponseType<typeof api_units_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                buildingId: params.buildingId === undefined ? undefined : String(params.buildingId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/units`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_units_list_list>
        }

        public async seed(): Promise<ResponseType<typeof api_units_seed_seed>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/units/seed`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_units_seed_seed>
        }

        public async update(params: RequestType<typeof api_units_update_update>): Promise<ResponseType<typeof api_units_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                balconyArea:     params.balconyArea,
                description:     params.description,
                floor:           params.floor,
                garageIncluded:  params.garageIncluded,
                millieme:        params.millieme,
                storageIncluded: params.storageIncluded,
                surfaceArea:     params.surfaceArea,
                unitNumber:      params.unitNumber,
                unitType:        params.unitType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/units/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_units_update_update>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
